<!-- 
Home Page (index.html)

This page should contain appropriate title, a description and graphic related to the company (with
company name, and logo). It is up to you to make up the details of the company that is advertising
the jobs. It should contain a menu that links to the other pages on your Web site. This same menu
should be in every page of your website with an email link to the companies email in the format of
info@companyname.com.au
In the footer include the link to your Jira Project (Don't forget to give access to your tutor) 
-->




<!-- Github live link:
    https://spudybro.github.io/HEMB/
-->



<!-- PHP code to set accessability preferences for the website -->
<?php
    include '../php/functionality.php';
?>









<!DOCTYPE html>
<html lang="en" class="<?php 
    set_accessibility();
    ?>">




    <head>
        <title>Home | HEMB-IT</title>
        <meta name="description" content="HEMB IT Solutions - Home Page">
        <meta name="keywords" content="HEMB, IT, Solutions, Home, Page, IT Support, Company">
        <meta name="author" content="Evan Harrision, Henry Bennett">
        <meta charset="UTF-8">
        <link rel="stylesheet" href="../styles/styles.css">
        <link rel="icon" type="image/x-icon" href="../images/fav_icon.webp">
        <!-- favicon partly generated by ChatGPT
                    was cropped and edited directly from the hero image
                   
                    reason for using GEN AI to create image:
                        (reasons are under hero image)
        -->

        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <header id="hero_img">
                <!-- Background generated by ChatGPT
                    Prompt provided:
                    "create me a hero image for my website hero image, with a modern simplistic feel for the website
                    1. IT Support company
                    2. A man in a suit
                    3. light theme
                    4. abstract or somthing"

                    reason for using GEN AI to create image:
                        1. our team does not have the graphic design skills to create a hero image
                        2. our team does not have the time to create a hero image
                        3. our team does not have the budget to pay someone to create a hero image
                -->

                <section id="hero_text">
                    <h1>HEMB IT Solutions</h1>
                    <p>Applying solutions that are sustainable</p>
                </section>

        </header>

        


        <?php 
        
        include '../inc/accessibility.inc';
        include '../inc/navigation.inc'; 
        
        ?>


        
        <main id="index_main">
            <!-- Main navigation menu that sticks to the top as you scroll down main
            Also note that when you reach the end of main, the nav menu will no longer follow 
            -->


            <section class="main_section index_section">
                <h2>What we do!</h2>
                <p>If you have any IT issues, we can fix them! Not everyone has the availability of having IT personnel to assist with small or large issues. That's why we are here! To bridge that gap and allow small to large companies to request assistance for cheap!</p>
                <!-- used gpt to find and fix grammar mistakes -->
                 
                <a href="./about.html">Learn More</a>
            </section>


            <section class="main_section index_section">
                <h2>IT support technicians for hire</h2>
                <p>Have the skills to be an IT support tech agent? Why not join us! We promise you a great and successful future filled with opportunities to grow, learn, and make a difference. Be part of a dynamic team that values innovation, collaboration, and excellence in providing top-notch IT solutions to our clients.</p>
                <!-- mostly generated by chatgpt 
                    prompt provided: make this longer
                    what was there before:
                    Have the skills to be a IT support tech agent? why not join us! We promise you a great and successful future

                    reason why i generated it:
                        i couldn't think of anything to say, and i wanted to make it longer
                        i also wanted to make it sound more professional and less like a 5 year old wrote it :p
                -->
                <a href="./jobs.html">Join us!</a>
            </section>


            <section class="main_section index_section">
                <h2>Meet our team</h2>
                <p>Our capable team members are the backbone of our success. Each individual brings a unique set of skills and experiences, contributing to the innovative solutions we provide. From troubleshooting complex IT issues to implementing cutting-edge technologies, our team is dedicated to delivering excellence. They are passionate about their work, committed to continuous learning, and always ready to go the extra mile to ensure client satisfaction. Meet the people who make it all happen and learn about their invaluable contributions to our company.</p>
                <!-- mostly generated by chatgpt 
                    prompt provided: make this longer
                    what was there before:
                    Our capable team members talk about their contributions to the company and their top tier skills

                    reason why i generated it:
                        i couldn't think of anything to say, and i wanted to make it longer
                        i also wanted to make it sound more professional and less like a 5 year old wrote it :p
                        yes its the same reasons as before...
                -->
                <a href="./about.html">Meet the team</a>
            </section>
                
            <section class="main_section index_section">
                <h2>Our Github Repository</h2>
                <p>Check out our Github repository to see our projects, contributions, and the innovative solutions we are working on. Collaborate with us and explore the world of IT support and development.</p>
                <!-- mostly generated by chatgpt 
                    prompt provided: make this longer
                    what was there before:
                    Check out our github repository

                    reason why i generated it:
                        i couldn't think of anything to say, and i wanted to make it longer
                        i also wanted to make it sound more professional and less like a 5 year old wrote it :p
                        im so creative XD
                -->
                <a href="https://github.com/SPUDYBRO/HEMB" target="_blank">Github</a>
            </section>


        </main>




        <?php 
            include '../inc/form_response.inc';
            # <!-- Footer Section -->
            include '../inc/footer.inc'; ?>

    </body>

</html>