<!-- PHP code to set accessability preferences for the website -->
<?php
    include '../php/functionality.php';
?>


<!DOCTYPE html>
<html lang="en" class="<?php 
    set_accessibility();
    ?>">


    <head>
        <title>Positions | HEMB-IT</title> <!-- Meta data -->
        <meta name="description" content="HEMB IT Solutions - Job Page - Position Descriptions">
        <meta name="keywords" content="HEMB, IT, Solutions - Job Page, Position Descriptions, 
        IT Support, IT Support Technician, IT Support Specialist, Desktop Support Technician, Service Desk Analyst">
        <meta name="author" content="Michael Sharpley, Evan Harrision, Henry Bennett">
        <meta charset="UTF-8">
        <link rel="stylesheet" href="../styles/styles.css">
        <link rel="icon" type="image/x-icon" href="../images/fav_icon.webp">
        <!-- favicon partly generated by ChatGPT
             was cropped and edited directly from the hero image
             
             reason for using GEN AI to create image:
                 (reasons are under hero image)
        -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        

        <?php 
        display_info_card();

        include '../inc/accessibility.inc';
        include '../inc/navigation.inc'; 
        ?>


        <!-- Aside -->
        <aside id="jobs_page_aside" class="main_section">
            <h2>Want to apply for a position?<br> Follow these tips first!</h2>
            <div>
                <h3>Resume</h3>
                <p>Putting all relevant work experience and education certificates will highly aid your chances on getting the job.</p>
            </div>
            <div>
                <h3>Interview Questions</h3>
                <p>Be prepared to answer a range of questions about your interest in IT, work ethic, job experience, and what you can bring to HEMB-IT.</p>
            </div>
        </aside>


        <main id="jobs_main">
            
            <h1>Position Descriptions</h1>
            <!-- Source: https://www.zippia.com/employer/how-to-write-a-job-description/  -->
            <hr>

            <?php
            require_once "settings.php";
            $dbconn = @mysqli_connect ($host,$user,$pwd,$sql_db);

            if ($dbconn) {
                $query = "SELECT * FROM jobs";
                $result = mysqli_query ($dbconn, $query);
                if ($result) {
                    while ($row = mysqli_fetch_assoc($result)) {
                        echo '<section class="main_section jobs_section">'
                        echo '<h2>' . $row['title'] . '</h2>'
                        echo '<p><strong>JOB TYPE:</strong>' . $row['type'] . '</p>'
                        echo '<p><strong>WORK HOURS:</strong>' . $row['work_hours'] . '</p>'
                        echo '<p><strong>SALARY:</strong>' . $row['salary'] . '</p>'
                        echo '<p><strong>SUPERVISOR:</strong>' . $row['supervisor'] . '</p>'
                        echo '<p><strong>POSITION DESCRIPTION REFERENCE NUMBER:</strong>' . $row['reference_number'] . '</p>'
                        echo '<br>'
                        echo '<p>' . $row['description'] . '</p>'
                        // echo '' . $row['responsibilities'] . ''
                        // echo '' . $row['essential_qualifications'] . ''
                        // echo '' . $row['preferable_qualifications'] . ''
                        echo '<h3>Benefits</h3>'
                        echo '' . $row['benefits'] . ''
                    }
                }
                else {
                    echo "There are no cars to display.";
                }
                mysqli_close($dbconn);
            } else echo "<p>Unable to connect to the db.</p>";
            
            echo '<section class="main_section jobs_section">'
            

            ?>
            <!-- JOB 1 / IT Support Technician -->
            <section class="main_section jobs_section">
                <h2>IT Support Technician</h2>
                <p><strong>JOB TYPE:</strong> Full Time</p>
                <p><strong>WORK HOURS:</strong> 9:00 AM - 5:00 PM, Monday - Friday</p>
                <p><strong>SALARY:</strong> $60,000 - $80,000</p>
                <p><strong>SUPERVISOR:</strong> IT Support Manager</p>
                <p><strong>POSITION DESCRIPTION REFERENCE NUMBER:</strong> IT300</p>
                <br>
                <p>As an IT Support Technician, you will provide IT support to a broad range of companies.</p>
                <!-- Source: https://www.jobsandskills.gov.au/data/occupation-and-industry-profiles/occupations/3131-ict-support-technicians  -->
                <!-- Source: https://itology.com/uncategorized/it-support-specialist-vs-it-technician-the-crucial-differences/  -->
                <!-- Source: https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC  -->
                <!-- Source: https://www.open.edu.au/advice/careers/it-computer-science/it-support-technician -->
                
                <!-- JOB 1 / Responsibilities -->
                <div>
                    <h3>Responsibilities:</h3>
                    <ul>
                        <li>Determining suitiable software and hardware solutions for clients.</li>
                        <li>Installing software to common operating systems.</li>
                        <li>Designing web sites using HTML5.</li>
                        <li>Advising clients on steps to take when encountering software or computer issues.</li>
                        <li>Identifing and responding to software and computer issues.</li>
                    </ul>
                </div>

                <!-- JOB 1 / Essential Qualifications -->
                <div>
                    <h3>Essential Qualifications:</h3>
                    <ol>
                        <li>Completed a suitable tertiary course in Information Technology.</li>
                        <!-- Source: https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC  -->
                        <li>1 year of work experience in an IT support position.</li>
                        <li>Proficiency in HTML5.</li>
                        <li>Proficiency in Python and Ruby.</li>
                        <li>Knowledge in Troubleshooting.</li>
                        <li>Understanding of Network Infrastructure.</li>
                        <li>Knowledge of Computer Hardware.</li>
                        <li>Proficiency in Operating Systems.</li>
                        <li>Knowledge of Security Practices.</li>
                        <li>Familiarity with Database Concepts.</li>
                    </ol>
                </div>

                <!-- JOB 1 / Preferable Qualifications -->
                <div>
                    <h3>Preferable Qualifications:</h3>
                    <ol>
                        <li>Prior work experience in customer support.</li>
                        <li>Work well unsupervised.</li>
                        <li>Passion in Information Technology.</li>
                    </ol>
                </div>

                <!-- JOB 1 / Benefits -->
                <div>
                    <h3>Benefits</h3>
                    <ul>
                        <li>20 days of Paid-Time-Off per year</li>
                        <!-- Source: https://www.fairwork.gov.au/leave/annual-leave -->
                    </ul>
                </div>
            </section>


            <!-- JOB 2 / IT Support Specialist -->
            <section class="main_section jobs_section"> 
                <h2>IT Support Specialist</h2>
                <p><strong>JOB TYPE:</strong> Full Time</p>
                <p><strong>WORK HOURS:</strong> 9:00 AM - 5:00 PM, Monday - Friday</p>
                <p><strong>SALARY:</strong> $60,000 - $80,000</p>
                <p><strong>SUPERVISOR:</strong> IT Support Manager</p>
                <p><strong>POSITION DESCRIPTION REFERENCE NUMBER:</strong> IT240</p>
                <br>
                <p>As an IT Support Specialist, you will give one-on-one software assistance to clients. You will also manage elements of HEMB-IT's cybersecurity</p>
                <!-- Source: https://itology.com/uncategorized/it-support-specialist-vs-it-technician-the-crucial-differences/  -->
                <!-- Source: https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC  -->
                
                <!-- JOB 2 / Responsibilities -->
                <div>
                    <h3>Responsibilities:</h3>
                    <ul>
                        <li>Provide support to questions asked on HEMB-IT's website.</li>
                        <li>Assist clients with cybersecurity and following legal regulations.</li>
                        <li>Determining suitiable software and hardware solutions for clients.</li>
                        <li>Advising clients on steps to take when encountering software or computer issues.</li>
                        <li>Identifing and responding to software and computer issues.</li>
                    </ul>
                </div>

                <!-- JOB 2 / Essential Qualifications -->
                <div>
                    <h3>Essential Qualifications:</h3>
                    <ol>
                        <li>Completed a suitable tertiary course in Information Technology.</li>
                        <!-- Source: https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC  -->
                        <li>1 year of work experience in an IT support position.</li>
                        <li>2 months of work experience in a customer support position.</li>
                        <li>Proficiency in HTML5.</li>
                        <li>Proficiency in Python and Ruby.</li>
                        <li>Knowledge in Troubleshooting.</li>
                        <li>Understanding of Network Infrastructure.</li>
                        <li>Knowledge of Computer Hardware.</li>
                        <li>Proficiency in Operating Systems.</li>
                        <li>Knowledge of Security Practices.</li>
                        <li>Familiarity with Database Concepts.</li>
                    </ol>
                </div>

                <!-- JOB 2 / Preferable Qualifications -->
                <div>
                    <h3>Preferable Qualifications:</h3>
                    <ol>
                        <li>Work well unsupervised.</li>
                        <li>Passion in Information Technology.</li>
                        <li>A strong understanding of software and hardware.</li>
                    </ol>
                </div>

                <!-- JOB 2 / Benefits -->
                <div>
                    <h3>Benefits</h3>
                    <ul>
                        <li>20 days of Paid-Time-Off per year</li>
                        <!-- Source: https://www.fairwork.gov.au/leave/annual-leave -->
                    </ul>
                </div>
            </section>
            <hr>


            <!-- JOB 3 / Desktop Support Technician -->
            <section class="main_section jobs_section"> 
                <h2>Desktop Support Technician</h2>
                <p><strong>JOB TYPE:</strong> Full Time</p>
                <p><strong>WORK HOURS:</strong> 9:00 AM - 5:00 PM, Monday - Friday</p>
                <p><strong>SALARY:</strong> $70,000 - $90,000</p>
                <p><strong>SUPERVISOR:</strong> Desktop Support Manager</p>
                <p><strong>POSITION DESCRIPTION REFERENCE NUMBER:</strong> IT350</p>
                <br>
                <p>As an Desktop Support Technician, your job is to maintain HEMB-IT's software and hardware needs in the office.</p>
                <!-- Source: https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC  -->

                <!-- JOB 3 / Responsibilities -->
                <div>
                    <h3>Responsibilities:</h3>
                    <ul>
                        <li>Ensure office computers work as intended.</li>
                        <li>Routinely test software and hardware </li>
                        <li>Provide support to coworkers </li>
                        <li>Installing software to office computers.</li>
                        <li>Provide training for new IT support employees.</li>
                        <li>Identifing and responding to software and computer issues.</li>
                        <li>Deploy hardware in the office.</li>
                    </ul>
                </div>

                <!-- JOB 3 / Essential Qualifications -->
                <div>
                    <h3>Essential Qualifications:</h3>
                    <ol>
                        <li>Completed a tertiary course in Networks and Switching.</li>
                        <!-- Source: https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC  -->
                        <!-- Source: https://www.tesla.com/careers/search/job/desktop-support-technician-237553 -->
                        <li>2 years of work experience in an IT support position.</li>
                        <li>Proficiency in Python and Ruby.</li>
                        <li>Indepth knowledge and experience in IP networks, DNS, and DHCP.</li>
                        <li>Experience in troubleshooting networks and switches.</li>
                        <li>Knowledge in Troubleshooting.</li>
                        <li>Understanding of Network Infrastructure.</li>
                        <li>Knowledge of Computer Hardware.</li>
                        <li>Proficiency in Operating Systems.</li>
                        <li>Knowledge of Security Practices.</li>
                        <li>Familiarity with Database Concepts.</li>
                    </ol>
                </div>

                <!-- JOB 3 / Preferable Qualifications -->
                <div>
                    <h3>Preferable Qualifications:</h3>
                    <ol>
                        <li>Work well unsupervised.</li>
                        <li>Passion in Information Technology.</li>
                        <li>A strong understanding of software and hardware.</li>
                    </ol>
                </div>

                <!-- JOB 3 / Benefits -->
                <h3>Benefits</h3>
                <ul>
                    <li>25 days of Paid-Time-Off per year</li>
                    <!-- Source: https://www.fairwork.gov.au/leave/annual-leave -->
                </ul>
            </section>
            <hr>


            <!-- JOB 4 / Service Desk Analyst -->
            <section class="main_section jobs_section">
                <h2>Service Desk Analyst</h2>
                <p><strong>JOB TYPE:</strong> Full Time</p>
                <p><strong>WORK HOURS:</strong> 9:00 AM - 5:00 PM, Monday - Friday</p>
                <p><strong>SALARY:</strong> $55,000 - $80,000</p>
                <!-- Source: https://au.indeed.com/q-service-desk-analyst-l-melbourne-vic-jobs.html?vjk=82f84d8b81617b4c -->
                <!-- Source: https://www.seek.com.au/career-advice/role/service-desk-analyst -->
                <!-- Source: https://au.indeed.com/career-advice/finding-a-job/what-does-a-desktop-support-technician-do -->
                <p><strong>SUPERVISOR:</strong> IT Support Manager</p>
                <p><strong>POSITION DESCRIPTION REFERENCE NUMBER:</strong> IT090</p>
                <br>
                <p>As an Service Desk Analyst, you will be resolving support tickets by clients.</p>
                <!-- Source: https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC  -->
                <!-- Source: https://www.seek.com.au/career-advice/role/service-desk-analyst -->
                <!-- Source: https://au.indeed.com/career-advice/finding-a-job/what-does-a-desktop-support-technician-do -->
                
                <!-- JOB 4 / Responsibilities -->
                <div>
                    <h3>Responsibilities:</h3>
                    <ul>
                        <li>Advising clients on steps to take when encountering software or computer issues.</li>
                        <li>Provide support to questions asked on HEMB-IT's website.</li>
                        <li>Assist clients with cybersecurity and following legal regulations.</li>
                        <li>Determining suitiable software and hardware solutions for clients.</li>
                    </ul>
                </div>

                <!-- JOB 4 / Essential Qualifications -->
                <div>
                    <h3>Essential Qualifications:</h3>
                    <ol>
                        <li>Completed a suitable tertiary course in Information Technology.</li>
                        <!-- Source: https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC  -->
                        <li>6 months of work experience in an IT support position.</li>
                        <li>6 months of work experience in a customer support position.</li>
                        <li>An indepth understanding of HTML5.</li>
                        <li>Knowledge in Troubleshooting.</li>
                        <li>Understanding of Network Infrastructure.</li>
                        <li>Knowledge of Computer Hardware.</li>
                        <li>Proficiency in Operating Systems.</li>
                        <li>Knowledge of Security Practices.</li>
                        <li>Familiarity with Database Concepts.</li>
                    </ol>
                </div>

                <!-- JOB 4 / Preferable Qualifications -->
                <div>
                    <h3>Preferable Qualifications:</h3>
                    <ol>
                        <li>Work well unsupervised.</li>
                        <li>Passion in Information Technology.</li>
                        <li>A strong understanding of software and hardware.</li>
                    </ol>
                </div>

                <!-- JOB 4 / Benefits -->
                <h3>Benefits</h3>
                <ul>
                    <li>20 days of Paid-Time-Off per year</li>
                    <!-- Source: https://www.fairwork.gov.au/leave/annual-leave -->
                </ul>
            </section>

        </main>


        <!-- Footer -->
        <?php 
            display_info_card();
            # <!-- Footer Section -->
            include '../inc/footer.inc'; ?>
    </body>
</html>