<section id="access_dropdown">
    <section id="dropdown_preview">
        <img src="../images/accessibility_icon.webp" alt="an image of a person with a disability icon">
    </section>
    <section id="dropdown_menu">
        <form method="get" action="../php/accessability.php">
            <button type="submit" name="accessibility" value="color_scheme" class="accessibility_button" title="Turn on/off color blindness mode">
                <img src="../images/colour_blind.webp" alt="An image of a black and white droplet symbolizing color blindness">
            </button>
        </form>
        
        <img src="../images/accessibility_icon.webp" alt="an image of a person with a disability icon"> <!-- these are placeholders until functionality is made -->
        <img src="../images/accessibility_icon.webp" alt="an image of a person with a disability icon">
    </section>
</section>