<!-- PHP code to set accessability preferences for the website -->
<?php
    include './php/functionality.php';
?>



<!DOCTYPE html>
<html lang="en" class="<?php 
    set_accessibility();
    ?>">


    <head>
        <title>Positions | HEMB-IT</title> <!-- Meta data -->
        <meta name="description" content="HEMB IT Solutions - Job Page containing a list of all 
        the available positions at HEMB IT Solutions. At the start of the page, there is a brief 
        overview if tips on how to aid your application process and general topics you will be 
        asked about in the interview. In addition, the page contains a list of all available positions
        at HEMB IT Solutions, with a description of the position, job type, work hours, salary, supervisor,
        position description reference number, responsibilities, essential qualifications, 
        preferable qualifications and benefits.">
        <meta name="keywords" content="HEMB, IT, Solutions - Job Page, Position Descriptions, 
        IT Support, IT Support Technician, IT Support Specialist, Desktop Support Technician, Service Desk Analyst">
        <meta name="author" content="Michael Sharpley, Evan Harrision, Henry Bennett">
        <meta charset="UTF-8">
        <link rel="stylesheet" href="./styles/styles.css">
        <link rel="icon" type="image/x-icon" href="./images/fav_icon.webp">
            <!--
            favicon partly generated by ChatGPT
            was cropped and edited directly from the hero image
             
            reason for using GEN AI to create image:
            (reasons are under hero image)
            -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>


    <body>
        

        <?php 
        display_info_card();
        include './inc/accessibility.inc';
        include './inc/navigation.inc'; 
        ?>


        <!-- Aside -->        
        <main id="jobs_main">

            <div id="jobs_header">

                <h1>Position Descriptions</h1>
                <aside id="jobs_page_aside" class="main_section">

                    <h2>Want to apply for a position?<br> Follow these tips first!</h2>
                    <div>
                        <h3>Resume</h3>
                        <p>Putting all relevant work experience and education certificates will highly aid your chances on getting the job.</p>
                    </div>

                    <div>
                        <h3>Interview Questions</h3>
                        <p>Be prepared to answer a range of questions about your interest in IT, work ethic, job experience, and what you can bring to HEMB-IT.</p>
                    </div>

                </aside>

            </div>
            <!-- Source: https://www.zippia.com/employer/how-to-write-a-job-description/  -->
            <hr>

            
            <?php
            require_once "./php/settings.php";
            $dbconn = @mysqli_connect ($host, $user, $pwd, $sql_db);

            if ($dbconn) {
                $query = "SELECT * FROM jobs";
                $result = mysqli_query ($dbconn, $query);

                if ($result) {
                    while ($row = mysqli_fetch_assoc($result)) {

                        echo '<section class="main_section jobs_section">';
                        echo '<h2>' . $row['title'] . '</h2>';
                        echo '<p><strong>JOB TYPE:</strong>' . $row['type'] . '</p>';
                        echo '<p><strong>WORK HOURS:</strong>' . $row['work_hours'] . '</p>';
                        echo '<p><strong>SALARY:</strong>' . $row['salary'] . '</p>';
                        echo '<p><strong>SUPERVISOR:</strong>' . $row['supervisor'] . '</p>';
                        echo '<p><strong>POSITION DESCRIPTION REFERENCE NUMBER:</strong>' . $row['reference_number'] . '</p>';
                        echo '<br>';
                        echo '<p>' . $row['description'] . '</p>';
                        
                        // Responsibilities
                        echo '<div><h3 class="jobs_h3">Responsibilities</h3>';
                        $output = '<ul>';
                        $items = explode('|', $row['responsibilities']);
                        foreach ($items as $item) {
                            $output .= '<li>' . $item . '</li>';
                        }  
                        $output .= '</ul></div>';
                        echo $output;

                        // Essential Qualifications
                        echo '<div><h3 class="jobs_h3">Essential Qualifications</h3>';
                        $output = '<ol>';
                        $items = explode('|', $row['essential_qualifications']);
                        foreach ($items as $item) {
                            $output .= '<li>' . $item . '</li>';
                        }  
                        $output .= '</ol></div>';
                        echo $output;

                        // Preferable Qualifications
                        echo '<div><h3 class="jobs_h3">Preferable Qualifications</h3>';
                        $output = '<ol>';
                        $items = explode('|', $row['preferable_qualifications']);
                        foreach ($items as $item) {
                            $output .= '<li>' . $item . '</li>';
                        }  
                        $output .= '</ol></div>';
                        echo $output;

                        // Benefits
                        echo '<div><h3 class="jobs_h3">Benefits</h3>';
                        echo '<ul></ul>';
                        echo '<li>' . $row['benefits'] . '</li></div>';
                        echo '</section>';

                    }

                }

                else {
                    echo "There are no jobs to display.";
                }

                mysqli_close($dbconn);
            } else echo "<p>Unable to connect to the db.</p>";
            ?>


            <!-- Sources: 
            https://www.jobsandskills.gov.au/data/occupation-and-industry-profiles/occupations/3131-ict-support-technicians  
            https://itology.com/uncategorized/it-support-specialist-vs-it-technician-the-crucial-differences/  
            https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC  
            https://www.open.edu.au/advice/careers/it-computer-science/it-support-technician 
            https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC
            https://www.fairwork.gov.au/leave/annual-leave
            https://itology.com/uncategorized/it-support-specialist-vs-it-technician-the-crucial-differences/ 
            https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC
            https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC
            https://au.indeed.com/q-service-desk-analyst-l-melbourne-vic-jobs.html?vjk=82f84d8b81617b4c
            https://www.seek.com.au/career-advice/role/service-desk-analyst
            https://au.indeed.com/career-advice/finding-a-job/what-does-a-desktop-support-technician-do
            https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC
            https://www.seek.com.au/career-advice/role/service-desk-analyst
            https://au.indeed.com/career-advice/finding-a-job/what-does-a-desktop-support-technician-do
            https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC
            https://www.fairwork.gov.au/leave/annual-leave
            https://www.seek.com.au/it-support-technician-jobs/in-All-Melbourne-VIC
            https://www.tesla.com/careers/search/job/desktop-support-technician-237553
            https://www.fairwork.gov.au/leave/annual-leave
            -->

        </main>


        <!-- Footer -->
        <?php 
            display_info_card();
            # <!-- Footer Section -->
            include './inc/footer.inc'; ?>


    </body>
    
</html>