# Workflow to deploy static site with project1 (HTML), style, and images folders
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Prepare deployment artifact
        run: |
          # Create a new folder for deploy artifact
          mkdir deploy
          # Copy HTML files from project1 into deploy so index.html lands at the root
          cp -r project1/* deploy/
          # Copy the styles and images folders (note: you are using "styles" for CSS)
          cp -r styles deploy/
          cp -r images deploy/
          # Update paths in HTML files: change "../styles/" to "styles/" and "../images/" to "images/"
          for file in deploy/*.html; do
            sed -i 's|\.\./styles/|styles/|g' "$file"
            sed -i 's|\.\./images/|images/|g' "$file"
          done
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Deploy the prepared folder
          path: deploy
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4







# This file was generated by GitHub Actions. and then further edited by ChatGPT
# Promp: I dont have a direct prompt as this took multiple messages to get to this point.
#
# reasons why i generated this file:
#   Github does not allow you to deploy a static site with a folder structure that is not the root of the repository or a docs folder.
#   I have a project1 folder that contains the HTML files and a styles and images folder that are not in the root of the repository.
#
#   I couldn't figure out how to deploy it any other way, and this seamed the easiest way to do it.
#
#   After a while of talking to ChatGPT, We decided on this solution although i am not sure if it is the best way to do it or what it is even doing
#
#   All i know is that it works and deploys the static site to github pages. so yay for that. 